services:
  - type: web
    name: jkanime-proxy
    env: node
    buildCommand: |
      npm install
      npx playwright install chromium
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
